name: CI
on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Use Node.js 12x

      - uses: actions/setup-node@v1
        name: Install
        with:
          node-version: '12.x'
      - run: npm install

      - uses: actions/setup-node@v1
        name: Integration Test 
      - run: yarn test
