name: CI Integration - Unit
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - uses: actions/checkout@v2
        name: Checkout
      
      - uses: actions/setup-node@v1
        name: Install dependencies
        with:
          node-version: '12.x'
      - run: yarn -i

      - uses: actions/setup-node@v1
        name: Run Tests Unit and Integration
        with:
          node-version: '12.x'
      - run: yarn test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
